site_name: RogueOne Docs
site_url: https://docs.rogueonemedia.com/
copyright: |
  &copy; 2023 RogueOne

theme:
  name: material
  icon:
    logo: fontawesome/brands/rebel
  features:
    - navigation.tabs
    - navigation.sections
    #- toc.integrate
    - toc.follow
    - navigation.footer
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  language: en
  palette:
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search:
      lang: en
  - glightbox: {}
    
nav:
  - Home: index.md
  - Getting Started: 
    - Emby: user-guide/emby.md
    - Ombi: user-guide/ombi.md
    - Send to Kindle: user-guide/send-to-kindle.md
  - Reference:
    - Internet Quality: reference/internet-quality.md
    - Subtitles: reference/subtitles.md